from typing import NamedTuple


class __Columns(NamedTuple):
    ADDRESS_ID: str = "address_id"
    AGE: str = "age"
    ALIVE: str = "alive"
    DEPENDENT_ID: str = "dependent_id"
    DOB: str = "date_of_birth"
    EMPLOYER_ADDRESS_ID: str = "employer_address_id"
    EMPLOYER_ID: str = "employer_id"
    EMPLOYER_NAME: str = "employer_name"
    EMPLOYER_PUMA: str = "employer_puma"
    EMPLOYER_STATE_ID: str = "employer_state_id"
    ENTRANCE_TIME: str = "entrance_time"
    EVENT_DATE: str = "event_date"
    EVENT_TYPE: str = "event_type"
    EXIT_TIME: str = "exit_time"
    FIRST_NAME_ID: str = "first_name_id"
    GUARDIAN_1: str = "guardian_1"
    GUARDIAN_2: str = "guardian_2"
    GUARDIAN_1_ADDRESS_ID: str = "guardian_1_address_id"
    GUARDIAN_2_ADDRESS_ID: str = "guardian_2_address_id"
    GUARDIAN_ID: str = "guardian_id"
    HAS_SSN: str = "has_ssn"
    HOUSEHOLD_ID: str = "household_id"
    HOUSING_TYPE: str = "housing_type"
    IN_UNITED_STATES: str = "in_united_states"
    INCOME: str = "income"
    JOINT_FILER: str = "joint_filer"
    LAST_NAME_ID: str = "last_name_id"
    MIDDLE_NAME_ID: str = "middle_name_id"
    PO_BOX: str = "po_box"
    PUMA: str = "puma"
    RACE_ETHNICITY: str = "race_ethnicity"
    RELATION_TO_HOUSEHOLD_HEAD: str = "relation_to_household_head"
    SEX: str = "sex"
    SIMULANT_ID: str = "simulant_id"
    SSN_ID: str = "ssn_id"
    STATE_ID: str = "state_id"
    SURVEY_DATE: str = "survey_date"
    TAX_FORM: str = "tax_form"
    TAX_YEAR: str = "tax_year"
    TRACKED: str = "tracked"
    YEAR: str = "year"


COLUMNS = __Columns()